# Generated by Django 4.0.6 on 2022-09-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindPartnerLetter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='letter',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
