# Generated by Django 4.1.1 on 2022-09-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FindPartnerLetter', '0003_userinfo_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='goal',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
